add samconfig
aws-samples/aws-batch-runtime-monitoring pull request #16
Opened 2022-06-08 10:12 UTC by fabiocesari

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-10 20:35 UTC, perifaws requested changes
Hi, just one file to remove and good to go

2022-08-10 20:35 UTC, perifaws commented on samconfig.toml
> +version = 0.1
Can we remove that from the PR? That's the case the `.gitignore` prevents :)

2022-08-16 01:09 UTC, adamantike commented on samconfig.toml
> +region = "eu-west-1"
Is there a way to not hardcode the region, and instead have SAM use the AWS account's default region?

2022-12-16 02:26 UTC, closed without merging

2022-12-16 02:26 UTC, perifaws commented
Closing due to no update.